'use client';

import React, { useState, useRef, useCallback } from 'react';
import { Upload, FileImage, FileVideo, FileAudio, FileText, Download,
         AlertTriangle, ShieldAlert, Loader2, ChevronRight, Lock, X } from 'lucide-react';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'https://dfd-back-exc0.onrender.com';

// ── Classification config (new three-class taxonomy) ─────────────────────────
const CLF_CONFIG = {
  REAL:          { color: '#10b981', bg: 'rgba(16,185,129,0.08)',  border: 'rgba(16,185,129,0.3)',  label: 'REAL',          icon: '✓' },
  AI_GENERATED:  { color: '#f59e0b', bg: 'rgba(245,158,11,0.08)', border: 'rgba(245,158,11,0.3)',  label: 'AI GENERATED',  icon: '⚠' },
  DEEPFAKE:      { color: '#ef4444', bg: 'rgba(239,68,68,0.08)',   border: 'rgba(239,68,68,0.3)',   label: 'DEEPFAKE',       icon: '✗' },
  UNKNOWN:       { color: '#6b7280', bg: 'rgba(107,114,128,0.08)', border: 'rgba(107,114,128,0.3)', label: 'UNKNOWN',        icon: '?' },
};

// Legacy fallback for results without classification field
const THREAT_CONFIG = {
  CRITICAL: { color: '#ef4444' }, HIGH: { color: '#f97316' },
  MODERATE: { color: '#f59e0b' }, LOW:  { color: '#84cc16' }, MINIMAL: { color: '#10b981' },
};

// Stage keys to show in breakdown — excludes internal scoring intermediates
const STAGE_DISPLAY = {
  frequency:       'Frequency Analysis',
  face_forensics:  'Face Forensics',
  manipulation:    'Manipulation',
  vehicle_damage:  'Vehicle Damage',
  deep_learning:   'DL Deepfake',
  dl_ai_generated: 'DL AI-Gen',
};

// Stage explanations shown to non-technical users
const STAGE_EXPLAIN = {
  frequency:       'Analyses the mathematical frequency patterns of the image. AI-generated images often lack the natural high-frequency noise of real cameras.',
  face_forensics:  'Examines face regions for signs of blending, boundary artifacts, resolution mismatches, and other face-swap indicators.',
  manipulation:    'Runs Error Level Analysis, copy-move detection, PRNU noise consistency, and metadata checks to find edited regions.',
  vehicle_damage:  'Compares ELA and texture across damage vs undamaged regions. AI-generated insurance damage has characteristic compression signatures.',
  deep_learning:   'Deep learning model trained on face deepfakes. High score = face-swap or GAN-generated face detected.',
  dl_ai_generated: 'AI-image detector model (sdxl-detector). High score = image was likely generated by an AI image generator.',
};

const FILE_ICONS = { IMAGE: FileImage, VIDEO: FileVideo, AUDIO: FileAudio, DOCUMENT: FileText };

function formatBytes(bytes) {
  if (!bytes) return '0 B';
  const k = 1024, sizes = ['B','KB','MB','GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${(bytes / Math.pow(k, i)).toFixed(2)} ${sizes[i]}`;
}

// ── Bubbles ───────────────────────────────────────────────────────────────────
function Bubbles() {
  const list = [
    { size:320, top:'-90px', left:'-70px', delay:'0s',   dur:'20s', op:0.45 },
    { size:180, top:'8%',    left:'72%',   delay:'2.5s', dur:'15s', op:0.35 },
    { size:260, top:'52%',   left:'-50px', delay:'4s',   dur:'22s', op:0.3  },
    { size:120, top:'28%',   left:'58%',   delay:'1s',   dur:'17s', op:0.28 },
    { size:210, top:'78%',   left:'78%',   delay:'3s',   dur:'24s', op:0.4  },
    { size:90,  top:'18%',   left:'32%',   delay:'5s',   dur:'13s', op:0.22 },
    { size:150, top:'82%',   left:'18%',   delay:'6s',   dur:'18s', op:0.3  },
    { size:100, top:'44%',   left:'88%',   delay:'0.8s', dur:'16s', op:0.25 },
  ];
  return (
    <div style={{ position:'fixed', inset:0, pointerEvents:'none', zIndex:0, overflow:'hidden' }}>
      {list.map((b,i) => (
        <div key={i} style={{
          position:'absolute', top:b.top, left:b.left, width:b.size, height:b.size,
          borderRadius:'50%',
          background:`radial-gradient(circle at 32% 32%, rgba(59,130,246,${b.op}) 0%, rgba(45,212,191,0.06) 55%, transparent 75%)`,
          border:'1px solid rgba(59,130,246,0.15)', backdropFilter:'blur(1px)',
          animation:`floatBubble ${b.dur} ease-in-out infinite`, animationDelay:b.delay,
          boxShadow:`inset 0 1px 0 rgba(255,255,255,0.08), 0 8px 32px rgba(59,130,246,0.06)`,
        }} />
      ))}
    </div>
  );
}

// ── Scanning panel ────────────────────────────────────────────────────────────
function ScanningPanel({ fileName }) {
  return (
    <div style={{
      background:'#0d1c35', border:'1px solid #1e2d4a', borderRadius:6,
      padding:'48px 32px', textAlign:'center', position:'relative', overflow:'hidden',
    }}>
      <div style={{
        position:'absolute', top:0, left:0, right:0, height:2,
        background:'linear-gradient(90deg, transparent, #00d4d4, transparent)',
        animation:'scanline 2.2s ease-in-out infinite',
      }} />
      <div style={{
        width:64, height:64, borderRadius:'50%', background:'rgba(0,212,212,0.1)',
        display:'flex', alignItems:'center', justifyContent:'center', margin:'0 auto 24px',
        animation:'pulse-ring 1.8s ease-out infinite',
      }}>
        <Loader2 size={28} color="#00d4d4" style={{ animation:'spin 1.2s linear infinite' }} />
      </div>
      <div style={{ fontFamily:'monospace', fontSize:13, color:'#00d4d4', letterSpacing:1.5, marginBottom:8, textTransform:'uppercase' }}>
        Running forensic analysis
      </div>
      <div style={{ color:'#8b949e', fontSize:14 }}>{fileName}</div>
    </div>
  );
}

// ── Dominant score display (replaces ScoreGauge) ──────────────────────────────
function VerdictHero({ result }) {
  // Prefer new classification fields; fall back to legacy for older responses
  const clf       = result.classification || (result.final_score >= 50 ? 'DEEPFAKE' : 'REAL');
  const cfg       = CLF_CONFIG[clf] || CLF_CONFIG.UNKNOWN;
  const domLabel  = result.dominant_label || `${result.final_score?.toFixed(1)}%`;
  const domScore  = result.dominant_score ?? result.final_score ?? 0;
  const riskLevel = result.risk_level || result.threat_level || '';

  // Score breakdown bars (ai_generated_score, deepfake_score, real_score)
  const tracks = [];
  if (result.ai_generated_score != null) tracks.push({ label:'AI Generated', val:result.ai_generated_score, color:'#f59e0b' });
  if (result.deepfake_score      != null) tracks.push({ label:'Deepfake',     val:result.deepfake_score,     color:'#ef4444' });
  if (result.real_score          != null) tracks.push({ label:'Real',         val:result.real_score,         color:'#10b981' });

  return (
    <div style={{
      background:cfg.bg, border:`1px solid ${cfg.border}`, borderRadius:8,
      padding:28, marginBottom:20,
    }}>
      <div style={{ display:'flex', gap:28, alignItems:'flex-start', flexWrap:'wrap' }}>

        {/* Dominant label — the headline number */}
        <div style={{ textAlign:'center', minWidth:160 }}>
          <div style={{
            fontSize:48, fontWeight:800, color:cfg.color, lineHeight:1,
            fontFamily:"'JetBrains Mono', monospace", letterSpacing:-1,
          }}>
            {domScore.toFixed(0)}%
          </div>
          <div style={{
            marginTop:8, display:'inline-block',
            fontSize:13, fontWeight:700, letterSpacing:2,
            color:cfg.color, border:`1px solid ${cfg.border}`,
            borderRadius:4, padding:'4px 12px', textTransform:'uppercase',
          }}>
            {cfg.icon} {cfg.label}
          </div>
          {riskLevel && (
            <div style={{ marginTop:6, fontSize:11, color:'#586069', letterSpacing:1 }}>
              {riskLevel} RISK
            </div>
          )}
        </div>

        {/* Three-track bar breakdown */}
        <div style={{ flex:1, minWidth:200 }}>
          {tracks.length > 0 && (
            <div style={{ marginBottom:16 }}>
              {tracks.map(t => (
                <div key={t.label} style={{ marginBottom:10 }}>
                  <div style={{ display:'flex', justifyContent:'space-between', fontSize:11, color:'#8b949e', marginBottom:4 }}>
                    <span>{t.label}</span><span style={{ color:t.color, fontWeight:700 }}>{t.val.toFixed(1)}%</span>
                  </div>
                  <div style={{ height:5, background:'#1e2d4a', borderRadius:3, overflow:'hidden' }}>
                    <div style={{ height:'100%', width:`${t.val}%`, background:t.color, borderRadius:3, transition:'width 1s ease' }} />
                  </div>
                </div>
              ))}
            </div>
          )}
          <p style={{ fontSize:14, lineHeight:1.7, margin:0, color:'#c9d1d9' }}>{result.verdict}</p>
          <div style={{ display:'flex', gap:8, marginTop:16 }}>
            <button onClick={() => window.open(`${API_BASE_URL}/report/${result.job_id}`, '_blank')}
              style={{ background:'#00d4d4', color:'#0a1628', border:'none', borderRadius:5, padding:'9px 16px', fontSize:13, fontWeight:700, cursor:'pointer', display:'flex', alignItems:'center', gap:6 }}>
              <Download size={13} /> PDF Report
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Stage breakdown with explanations ─────────────────────────────────────────
function StageBreakdown({ stageScores }) {
  const [expanded, setExpanded] = useState(null);
  if (!stageScores) return null;

  const entries = Object.entries(stageScores).filter(([k, v]) =>
    v !== null && v !== undefined && STAGE_DISPLAY[k]
  );
  if (!entries.length) return null;

  return (
    <div style={{ marginBottom:20 }}>
      <h3 style={{ fontSize:12, color:'#586069', letterSpacing:1, textTransform:'uppercase', marginBottom:12 }}>
        Stage breakdown — click any stage for explanation
      </h3>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(140px, 1fr))', gap:10 }}>
        {entries.map(([key, val]) => {
          const isExp = expanded === key;
          const color = val >= 65 ? '#ef4444' : val >= 40 ? '#f59e0b' : '#10b981';
          return (
            <div key={key} onClick={() => setExpanded(isExp ? null : key)}
              style={{
                background:'#0d1c35', border:`1px solid ${isExp ? '#2dd4bf' : '#1e2d4a'}`,
                borderRadius:6, padding:14, cursor:'pointer', transition:'border-color 0.2s',
              }}>
              <div style={{ fontSize:11, color:'#586069', marginBottom:6, textTransform:'uppercase', letterSpacing:0.5 }}>
                {STAGE_DISPLAY[key]}
              </div>
              <div style={{ fontFamily:'monospace', fontSize:22, fontWeight:700, color, marginBottom:6 }}>
                {typeof val === 'number' ? `${val}%` : val}
              </div>
              <div style={{ height:3, background:'#1e2d4a', borderRadius:2, overflow:'hidden' }}>
                <div style={{ height:'100%', width:`${Math.min(val,100)}%`, background:color, borderRadius:2 }} />
              </div>
              {isExp && STAGE_EXPLAIN[key] && (
                <div style={{ marginTop:10, fontSize:12, color:'#8b949e', lineHeight:1.5, borderTop:'1px solid #1e2d4a', paddingTop:10 }}>
                  {STAGE_EXPLAIN[key]}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ── Lightbox ──────────────────────────────────────────────────────────────────
function Lightbox({ src, onClose }) {
  if (!src) return null;
  return (
    <div onClick={onClose} style={{
      position:'fixed', inset:0, background:'rgba(0,0,0,0.9)', zIndex:1000,
      display:'flex', alignItems:'center', justifyContent:'center', cursor:'zoom-out',
    }}>
      <img src={src} alt="" style={{ maxWidth:'92vw', maxHeight:'92vh', borderRadius:8, boxShadow:'0 24px 80px rgba(0,0,0,0.6)' }} />
      <button onClick={onClose} style={{
        position:'absolute', top:20, right:20, background:'rgba(255,255,255,0.1)',
        border:'none', borderRadius:'50%', width:36, height:36, cursor:'pointer',
        color:'#fff', fontSize:18, display:'flex', alignItems:'center', justifyContent:'center',
      }}><X size={16} /></button>
    </div>
  );
}

// ── Graphs grid ───────────────────────────────────────────────────────────────
function GraphsGrid({ graphs, jobId }) {
  const [lightbox, setLightbox] = useState(null);
  if (!graphs?.length) return null;

  const getSrc = (g) => {
    if (g.filename && jobId) return `${API_BASE_URL}/graph/${jobId}/${g.filename}`;
    if (g.image_b64)         return `data:image/png;base64,${g.image_b64}`;
    return null;
  };

  return (
    <>
      <Lightbox src={lightbox} onClose={() => setLightbox(null)} />
      <div style={{ marginBottom:20 }}>
        <h3 style={{ fontSize:12, color:'#586069', letterSpacing:1, textTransform:'uppercase', marginBottom:12 }}>
          Visual analysis — click to expand
        </h3>
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:14 }}>
          {graphs.map((g, i) => {
            const src = getSrc(g);
            return (
              <div key={i} style={{ background:'#0d1c35', border:'1px solid #1e2d4a', borderRadius:6, overflow:'hidden', cursor: src ? 'zoom-in' : 'default' }}
                onClick={() => src && setLightbox(src)}>
                <div style={{ aspectRatio:'16/10', background:'#0a1628', display:'flex', alignItems:'center', justifyContent:'center' }}>
                  {src
                    ? <img src={src} alt={g.title} style={{ width:'100%', height:'100%', objectFit:'cover' }} />
                    : <span style={{ fontSize:11, color:'#3d5070', fontFamily:'monospace' }}>[ loading ]</span>
                  }
                </div>
                <div style={{ padding:'10px 12px' }}>
                  <div style={{ fontSize:12, fontWeight:600, color:'#e6edf3', marginBottom:3 }}>{g.title}</div>
                  <div style={{ fontSize:11, color:'#586069', lineHeight:1.5 }}>{g.description}</div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
}

// ── Main app ──────────────────────────────────────────────────────────────────
export default function DeepfakeDetectorApp() {
  const [stage, setStage]       = useState('upload');
  const [file, setFile]         = useState(null);
  const [progress, setProgress] = useState(0);
  const [result, setResult]     = useState(null);
  const [errorMsg, setErrorMsg] = useState('');
  const [dragActive, setDragActive] = useState(false);
  const fileInputRef       = useRef(null);
  const progressIntervalRef = useRef(null);

  const handleFileSelect = useCallback((f) => { if (f) setFile(f); }, []);
  const handleDrag = (e) => {
    e.preventDefault(); e.stopPropagation();
    setDragActive(e.type === 'dragenter' || e.type === 'dragover');
  };
  const handleDrop = (e) => {
    e.preventDefault(); e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files?.[0]) handleFileSelect(e.dataTransfer.files[0]);
  };

  const startAnalysis = async () => {
    if (!file) return;
    setStage('scanning'); setProgress(0); setErrorMsg('');
    progressIntervalRef.current = setInterval(() => {
      setProgress(p => p < 92 ? p + Math.random() * 8 : p);
    }, 400);
    try {
      const fd = new FormData();
      fd.append('file', file);
      const res = await fetch(`${API_BASE_URL}/analyze`, {
        method:'POST', headers:{'ngrok-skip-browser-warning':'true'}, body:fd,
      });
      if (!res.ok) throw new Error(`Server returned ${res.status}`);
      const data = await res.json();
      clearInterval(progressIntervalRef.current);
      setProgress(100);
      if (data.error) { setTimeout(() => { setErrorMsg(data.error); setStage('error'); }, 400); return; }
      setTimeout(() => { setResult(data); setStage('results'); }, 500);
    } catch (err) {
      clearInterval(progressIntervalRef.current);
      setErrorMsg(`Could not reach the analysis server. It may be waking up — please wait 60 seconds and try again. (${err.message})`);
      setStage('error');
    }
  };

  const reset = () => { setStage('upload'); setFile(null); setProgress(0); setResult(null); setErrorMsg(''); };

  return (
    <div style={{ minHeight:'100vh', background:'#0a1628', color:'#e6edf3', fontFamily:"'Inter', -apple-system, sans-serif", position:'relative' }}>
      <style>{`
        * { box-sizing:border-box; }
        ::selection { background:#00d4d4; color:#0a1628; }
        @keyframes floatBubble { 0%,100%{transform:translateY(0) scale(1);} 33%{transform:translateY(-20px) scale(1.02);} 66%{transform:translateY(12px) scale(0.98);} }
        @keyframes scanline { 0%{transform:translateY(0);opacity:0.3;} 50%{opacity:1;} 100%{transform:translateY(400px);opacity:0.3;} }
        @keyframes pulse-ring { 0%{box-shadow:0 0 0 0 rgba(0,212,212,0.4);} 100%{box-shadow:0 0 0 16px rgba(0,212,212,0);} }
        @keyframes spin { to{transform:rotate(360deg);} }
        @keyframes fadeIn { from{opacity:0;transform:translateY(10px);} to{opacity:1;transform:translateY(0);} }
      `}</style>

      <Bubbles />

      {/* HEADER */}
      <header style={{
        borderBottom:'1px solid #1e2d4a', padding:'16px 32px',
        display:'flex', alignItems:'center', justifyContent:'space-between',
        background:'rgba(10,22,40,0.88)', backdropFilter:'blur(12px)',
        position:'sticky', top:0, zIndex:100,
      }}>
        <div style={{ display:'flex', alignItems:'center', gap:10 }}>
          <ShieldAlert size={20} color="#00d4d4" />
          <div style={{ display:'flex', flexDirection:'column', gap:1 }}>
            <span style={{ fontSize:9, fontWeight:600, color:'#00d4d4', letterSpacing:2, textTransform:'uppercase', lineHeight:1 }}>AlgorivX.AI</span>
            <span style={{ fontWeight:800, fontSize:20, letterSpacing:-0.5, color:'#e6edf3', lineHeight:1 }}>Darpan</span>
          </div>
          <span style={{ fontFamily:'monospace', fontSize:10, color:'#00d4d4', border:'1px solid #1e2d4a', padding:'2px 6px', borderRadius:3, alignSelf:'flex-end', marginBottom:1 }}>
            FORENSIC ENGINE v 1.0
          </span>
        </div>
        <div style={{ display:'flex', alignItems:'center', gap:14, fontSize:13, color:'#8b949e' }}>
          {result && <button onClick={reset} style={{ background:'transparent', color:'#8b949e', border:'1px solid #1e2d4a', borderRadius:5, padding:'7px 12px', fontSize:12, cursor:'pointer' }}>New analysis</button>}
          <span>Pro Plan</span>
          <div style={{ width:28, height:28, borderRadius:'50%', background:'#1e2d4a', display:'flex', alignItems:'center', justifyContent:'center', fontSize:12, fontWeight:600 }}>U</div>
        </div>
      </header>

      <main style={{ maxWidth:960, margin:'0 auto', padding:'40px 24px 60px', position:'relative', zIndex:1 }}>

        {/* ── UPLOAD ── */}
        {stage === 'upload' && (
          <div style={{ animation:'fadeIn 0.4s ease' }}>
            <div style={{ marginBottom:32 }}>
              <h1 style={{ fontSize:28, fontWeight:700, margin:0, letterSpacing:-0.5 }}>Submit a file for analysis</h1>
              <p style={{ color:'#8b949e', fontSize:15, marginTop:8 }}>
                Images, video, audio, and documents. Multi-stage forensic pipeline — frequency analysis, face forensics, deep learning.
              </p>
            </div>

            <div onDragEnter={handleDrag} onDragLeave={handleDrag} onDragOver={handleDrag} onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
              style={{
                border:`2px dashed ${dragActive ? '#00d4d4' : '#1e2d4a'}`, borderRadius:8,
                padding:'56px 24px', textAlign:'center', cursor:'pointer',
                background: dragActive ? 'rgba(0,212,212,0.04)' : '#0d1c35', transition:'all 0.15s ease',
              }}>
              <input ref={fileInputRef} type="file" style={{ display:'none' }}
                onChange={e => handleFileSelect(e.target.files?.[0])}
                accept=".jpg,.jpeg,.png,.bmp,.tiff,.webp,.mp4,.avi,.mov,.mkv,.webm,.mp3,.wav,.aac,.flac,.ogg,.m4a,.pdf,.docx,.txt" />
              <Upload size={32} color="#00d4d4" style={{ marginBottom:16 }} />
              <div style={{ fontSize:16, fontWeight:600, marginBottom:6 }}>
                {file ? file.name : 'Drop a file here, or click to browse'}
              </div>
              <div style={{ fontSize:13, color:'#586069' }}>
                {file ? formatBytes(file.size) : 'JPG · PNG · MP4 · MOV · MP3 · WAV · PDF · DOCX — up to 500 MB'}
              </div>
            </div>

            {file && (
              <div style={{ marginTop:16, display:'flex', gap:10 }}>
                <button onClick={startAnalysis} style={{ background:'#00d4d4', color:'#0a1628', border:'none', borderRadius:5, padding:'12px 24px', fontSize:14, fontWeight:700, cursor:'pointer', display:'flex', alignItems:'center', gap:8 }}>
                  Run analysis <ChevronRight size={16} />
                </button>
                <button onClick={() => setFile(null)} style={{ background:'transparent', color:'#8b949e', border:'1px solid #1e2d4a', borderRadius:5, padding:'12px 18px', fontSize:14, cursor:'pointer' }}>Clear</button>
              </div>
            )}

            <div style={{ marginTop:48, display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:12 }}>
              {[
                { icon:FileImage, label:'Images',    desc:'Frequency · Face · DL ensemble' },
                { icon:FileVideo, label:'Video',     desc:'Frame · Temporal consistency' },
                { icon:FileAudio, label:'Audio',     desc:'Voice clone · TTS detection' },
                { icon:FileText,  label:'Documents', desc:'AI-generated text detection' },
              ].map(item => (
                <div key={item.label} style={{ background:'#0d1c35', border:'1px solid #1e2d4a', borderRadius:6, padding:16 }}>
                  <item.icon size={18} color="#00d4d4" style={{ marginBottom:10 }} />
                  <div style={{ fontSize:13, fontWeight:600 }}>{item.label}</div>
                  <div style={{ fontSize:12, color:'#586069', marginTop:4 }}>{item.desc}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── SCANNING ── */}
        {stage === 'scanning' && (
          <div style={{ animation:'fadeIn 0.3s ease' }}>
            <ScanningPanel fileName={file?.name} />
          </div>
        )}

        {/* ── ERROR ── */}
        {stage === 'error' && (
          <div style={{ background:'#0d1c35', border:'1px solid #ef4444', borderRadius:8, padding:32, textAlign:'center', animation:'fadeIn 0.3s ease' }}>
            <AlertTriangle size={28} color="#ef4444" style={{ marginBottom:16 }} />
            <div style={{ fontSize:16, fontWeight:600, marginBottom:8 }}>Analysis failed</div>
            <div style={{ fontSize:14, color:'#8b949e', marginBottom:24 }}>{errorMsg}</div>
            <button onClick={reset} style={{ background:'#1e2d4a', color:'#e6edf3', border:'none', borderRadius:5, padding:'10px 20px', fontSize:14, cursor:'pointer' }}>Try another file</button>
          </div>
        )}

        {/* ── RESULTS ── */}
        {stage === 'results' && result && (
          <div style={{ animation:'fadeIn 0.4s ease' }}>

            {/* Verdict hero — dominant classification */}
            <VerdictHero result={result} />

            {/* File info bar */}
            <div style={{ display:'flex', alignItems:'center', gap:10, padding:'10px 14px', background:'#0d1c35', border:'1px solid #1e2d4a', borderRadius:6, marginBottom:20, fontFamily:'monospace', fontSize:12, color:'#586069', flexWrap:'wrap' }}>
              {React.createElement(FILE_ICONS[result.file_type] || FileText, { size:13, color:'#00d4d4' })}
              <span style={{ color:'#e6edf3' }}>{result.filename}</span>
              <span>·</span><span>{result.file_type}</span>
              <span>·</span><span>{formatBytes(result.metadata?.size_bytes)}</span>
              <span>·</span><span>Job {result.job_id}</span>
              {result.fusion_mode && <><span>·</span><span style={{ color:'#3d5070' }}>{result.fusion_mode}</span></>}
            </div>

            {/* Stage breakdown with explanations */}
            <StageBreakdown stageScores={result.stage_scores} />

            {/* Flagged indicators */}
            {result.indicators?.length > 0 && (
              <div style={{ marginBottom:20 }}>
                <h3 style={{ fontSize:12, color:'#586069', letterSpacing:1, textTransform:'uppercase', marginBottom:12 }}>
                  Flagged indicators ({result.indicators.length})
                </h3>
                <div style={{ background:'#0d1c35', border:'1px solid #1e2d4a', borderRadius:6, overflow:'hidden' }}>
                  {result.indicators.map((ind, i) => (
                    <div key={i} style={{ display:'flex', alignItems:'flex-start', gap:10, padding:'10px 14px', fontSize:13, borderBottom: i < result.indicators.length-1 ? '1px solid #1e2d4a' : 'none' }}>
                      <AlertTriangle size={13} color="#f59e0b" style={{ flexShrink:0, marginTop:1 }} />
                      <span style={{ color:'#c9d1d9', lineHeight:1.5 }}>{ind}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Visual analysis graphs */}
            <GraphsGrid graphs={result.graphs} jobId={result.job_id} />

            {/* Detailed metrics */}
            {result.stats?.length > 0 && (
              <div style={{ marginBottom:20 }}>
                <h3 style={{ fontSize:12, color:'#586069', letterSpacing:1, textTransform:'uppercase', marginBottom:12 }}>Detailed metrics</h3>
                <div style={{ display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:8 }}>
                  {result.stats.map((s, i) => (
                    <div key={i} style={{ background:'#0d1c35', border:'1px solid #1e2d4a', borderRadius:6, padding:'10px 12px' }}>
                      <div style={{ fontSize:10, color:'#586069', marginBottom:3 }}>{s.label}</div>
                      <div style={{ fontFamily:'monospace', fontSize:13, color:'#e6edf3' }}>{s.value}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* File evidence */}
            <div>
              <h3 style={{ fontSize:12, color:'#586069', letterSpacing:1, textTransform:'uppercase', marginBottom:12 }}>
                <Lock size={11} style={{ display:'inline', marginRight:5, verticalAlign:-1 }} /> File evidence
              </h3>
              <div style={{ background:'#0d1c35', border:'1px solid #1e2d4a', borderRadius:6, padding:14, fontFamily:'monospace', fontSize:11, color:'#586069', lineHeight:2 }}>
                <div><span style={{ color:'#3d5070', marginRight:8 }}>MD5</span>{result.metadata?.md5}</div>
                <div><span style={{ color:'#3d5070', marginRight:8 }}>SHA256</span>{result.metadata?.sha256}</div>
                <div><span style={{ color:'#3d5070', marginRight:8 }}>MIME</span>{result.metadata?.mime}</div>
                <div><span style={{ color:'#3d5070', marginRight:8 }}>TIME</span>{result.metadata?.analyzed_at}</div>
              </div>
            </div>

          </div>
        )}
      </main>
    </div>
  );
}
