'use client';

import React, { useState, useRef, useCallback, useEffect } from 'react';
import { Upload, FileImage, FileVideo, FileAudio, FileText, Download,
         AlertTriangle, ShieldAlert, Loader2, ChevronRight, Lock, X } from 'lucide-react';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'https://dfd-back-exc0.onrender.com';

// ── Auth ───────────────────────────────────────────────────────────────────
// Backend v6.0 requires a JWT (or API key) on /analyze, /graph, /report, /jobs.
// Token is persisted in localStorage so a page refresh doesn't force re-login —
// this is a real deployed app (not a Claude artifact sandbox), so localStorage
// is the normal, correct choice here.
const AUTH_STORAGE_KEY = 'darpan_auth';

async function authFetch(path, token, options = {}) {
  return fetch(`${API_BASE_URL}${path}`, {
    ...options,
    headers: { ...(options.headers || {}), Authorization: `Bearer ${token}` },
  });
}

// ── Surface elevation tokens ──────────────────────────────────────────────────
// Previously page bg (#070f1f) and card bg (#13294a) were only ~3 points apart in
// lightness — contrast ratio 1.07:1, visually almost identical. Header, stat tiles,
// and graph thumbnails all merged into the page background as a result.
// Replaced with a real elevation ladder: same navy hue family, increasing lightness
// per layer, so the eye can tell what's "on top of" what.
const SURFACE = {
  page:    '#070f1f',  // outer page — recedes
  header:  '#0f213d',  // sticky header — distinct from page
  card:    '#13294a',  // stat tiles, indicator rows, file info bar
  raised:  '#18305a',  // graph thumbnails, expanded/hover states — most "raised"
  border:  '#234268',  // card borders — was #234268, barely visible against old bg
  borderHeader: '#1e3a5f',
};

// ── Classification config (new three-class taxonomy) ─────────────────────────
const CLF_CONFIG = {
  REAL:          { color: '#10b981', bg: 'rgba(16,185,129,0.08)',  border: 'rgba(16,185,129,0.3)',  label: 'REAL',          icon: '✓' },
  // REAL_EDITED: sub-class of REAL — genuine content, evidence of post-processing.
  // Amber tone distinguishes it from clean REAL (green) without implying fabrication.
  REAL_EDITED:   { color: '#f59e0b', bg: 'rgba(245,158,11,0.06)', border: 'rgba(245,158,11,0.25)', label: 'REAL (Edited)', icon: '✎' },
  AI_GENERATED:  { color: '#f59e0b', bg: 'rgba(245,158,11,0.08)', border: 'rgba(245,158,11,0.3)',  label: 'AI GENERATED',  icon: '⚠' },
  DEEPFAKE:      { color: '#ef4444', bg: 'rgba(239,68,68,0.08)',   border: 'rgba(239,68,68,0.3)',   label: 'DEEPFAKE',       icon: '✗' },
  UNKNOWN:       { color: '#6b7280', bg: 'rgba(107,114,128,0.08)', border: 'rgba(107,114,128,0.3)', label: 'UNKNOWN',        icon: '?' },
};

// Legacy fallback for results without classification field
const THREAT_CONFIG = {
  CRITICAL: { color: '#ef4444' }, HIGH: { color: '#f97316' },
  MODERATE: { color: '#f59e0b' }, LOW:  { color: '#84cc16' }, MINIMAL: { color: '#10b981' },
};

// Stage keys to show in breakdown — excludes internal scoring intermediates
const STAGE_DISPLAY = {
  frequency:        'Frequency Analysis',
  face_forensics:   'Face Forensics',
  manipulation:     'Manipulation',
  vehicle_damage:   'Vehicle Damage',
  deep_learning:    'DL Deepfake',
  dl_ai_generated:  'DL AI-Gen',
  exif_edit_score:  'EXIF Edit Signal',
};

// Plain-language names for the verdict explanation sentence — technical stage
// names (DL Deepfake, EXIF Edit Signal) read fine in a tile, but sound like
// jargon in a sentence aimed at a non-technical user. Falls back to
// STAGE_DISPLAY's name if a key isn't listed here.
const STAGE_PLAIN_NAME = {
  frequency:        'image-pattern check',
  face_forensics:   'face match check',
  manipulation:     'editing-traces check',
  vehicle_damage:   'damage-photo check',
  deep_learning:    'face-swap detector',
  dl_ai_generated:  'AI-image detector',
  exif_edit_score:  'editing-software check',
};

// Stage explanations shown to non-technical users
const STAGE_EXPLAIN = {
  frequency:        'Analyses the mathematical frequency patterns of the image. AI-generated images often lack the natural high-frequency noise of real cameras.',
  face_forensics:   'Examines face regions for signs of blending, boundary artifacts, resolution mismatches, and other face-swap indicators.',
  manipulation:     'Runs Error Level Analysis, copy-move detection, PRNU noise consistency, and metadata checks to find edited regions.',
  vehicle_damage:   'Compares ELA and texture across damage vs undamaged regions. AI-generated insurance damage has characteristic compression signatures.',
  deep_learning:    'Deep learning model trained on face deepfakes. High score = face-swap or GAN-generated face detected.',
  dl_ai_generated:  'AI-image detector model (sdxl-detector). High score = image was likely generated by an AI image generator.',
  exif_edit_score:  'Measures signals in the image metadata consistent with professional editing software (Photoshop, Lightroom, GIMP, etc). A high score indicates the image was processed or colour-graded after capture — this does not indicate AI generation or deepfake.',
};

const FILE_ICONS = { IMAGE: FileImage, VIDEO: FileVideo, AUDIO: FileAudio, DOCUMENT: FileText };

function formatBytes(bytes) {
  if (!bytes) return '0 B';
  const k = 1024, sizes = ['B','KB','MB','GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${(bytes / Math.pow(k, i)).toFixed(2)} ${sizes[i]}`;
}

// ── Bubbles ───────────────────────────────────────────────────────────────────
function Bubbles() {
  const list = [
    { size:320, top:'-90px', left:'-70px', delay:'0s',   dur:'20s', op:0.45 },
    { size:180, top:'8%',    left:'72%',   delay:'2.5s', dur:'15s', op:0.35 },
    { size:260, top:'52%',   left:'-50px', delay:'4s',   dur:'22s', op:0.3  },
    { size:120, top:'28%',   left:'58%',   delay:'1s',   dur:'17s', op:0.28 },
    { size:210, top:'78%',   left:'78%',   delay:'3s',   dur:'24s', op:0.4  },
    { size:90,  top:'18%',   left:'32%',   delay:'5s',   dur:'13s', op:0.22 },
    { size:150, top:'82%',   left:'18%',   delay:'6s',   dur:'18s', op:0.3  },
    { size:100, top:'44%',   left:'88%',   delay:'0.8s', dur:'16s', op:0.25 },
  ];
  return (
    <div style={{ position:'fixed', inset:0, pointerEvents:'none', zIndex:0, overflow:'hidden' }}>
      {list.map((b,i) => (
        <div key={i} style={{
          position:'absolute', top:b.top, left:b.left, width:b.size, height:b.size,
          borderRadius:'50%',
          background:`radial-gradient(circle at 32% 32%, rgba(59,130,246,${b.op}) 0%, rgba(45,212,191,0.06) 55%, transparent 75%)`,
          border:'1px solid rgba(59,130,246,0.15)', backdropFilter:'blur(1px)',
          animation:`floatBubble ${b.dur} ease-in-out infinite`, animationDelay:b.delay,
          boxShadow:`inset 0 1px 0 rgba(255,255,255,0.08), 0 8px 32px rgba(59,130,246,0.06)`,
        }} />
      ))}
    </div>
  );
}

// ── Scanning panel ────────────────────────────────────────────────────────────
function ScanningPanel({ fileName }) {
  return (
    <div style={{
      background:'#13294a', border:'1px solid #234268', borderRadius:6,
      padding:'48px 32px', textAlign:'center', position:'relative', overflow:'hidden',
    }}>
      <div style={{
        position:'absolute', top:0, left:0, right:0, height:2,
        background:'linear-gradient(90deg, transparent, #00d4d4, transparent)',
        animation:'scanline 2.2s ease-in-out infinite',
      }} />
      <div style={{
        width:64, height:64, borderRadius:'50%', background:'rgba(0,212,212,0.1)',
        display:'flex', alignItems:'center', justifyContent:'center', margin:'0 auto 24px',
        animation:'pulse-ring 1.8s ease-out infinite',
      }}>
        <Loader2 size={28} color="#00d4d4" style={{ animation:'spin 1.2s linear infinite' }} />
      </div>
      <div style={{ fontFamily:'monospace', fontSize:13, color:'#00d4d4', letterSpacing:1.5, marginBottom:8, textTransform:'uppercase' }}>
        Running forensic analysis
      </div>
      <div style={{ color:'#8b949e', fontSize:14 }}>{fileName}</div>
    </div>
  );
}

// ── Dominant score display (replaces ScoreGauge) ──────────────────────────────
function VerdictHero({ result, authToken }) {
  // Prefer new classification fields; fall back to legacy for older responses.
  // When backend sets editing_detected=true on a REAL result, promote to REAL_EDITED
  // for display purposes only — the underlying classification field stays 'REAL'.
  const clfRaw    = result.classification || (result.final_score >= 50 ? 'DEEPFAKE' : 'REAL');
  const clf       = (clfRaw === 'REAL' && result.editing_detected) ? 'REAL_EDITED' : clfRaw;
  const cfg       = CLF_CONFIG[clf] || CLF_CONFIG.UNKNOWN;
  const domLabel  = result.dominant_label || `${result.final_score?.toFixed(1)}%`;
  const domScore  = result.dominant_score ?? result.final_score ?? 0;
  const riskLevel = result.risk_level || result.threat_level || '';

  // Score breakdown bars (ai_generated_score, deepfake_score, real_score / edited_score)
  const tracks = [];
  if (result.ai_generated_score != null) tracks.push({ label:'AI Generated', val:result.ai_generated_score, color:'#f59e0b' });
  if (result.deepfake_score      != null) tracks.push({ label:'Deepfake',     val:result.deepfake_score,     color:'#ef4444' });
  // For REAL (Edited) results, swap in an 'Edit Signal' bar in place of plain Real.
  // This makes the bar visually meaningful — the editing signal that fired is shown.
  if (result.editing_detected && result.edited_score != null) {
    tracks.push({ label:'Edit Signal', val:result.edited_score, color:'#f59e0b' });
  } else if (result.real_score != null) {
    tracks.push({ label:'Real',        val:result.real_score,   color:'#10b981' });
  }

  // ── Plain-language headline explanation ─────────────────────────────────
  // Addresses real user confusion: the headline is a blended composite of
  // several stage scores, so it often doesn't match the single highest stage
  // tile (e.g. a 77% face-swap-detector score producing a 65% headline).
  // This computes which stage score is doing the most work and explains the
  // gap in one plain sentence, in non-technical language. Only shown when
  // the gap is meaningful (>8 points) — otherwise the headline already
  // tracks the dominant signal closely enough that an explanation adds noise.
  let dominantExplain = null;
  if (result.stage_scores) {
    const numericStages = Object.entries(result.stage_scores)
      .filter(([k, v]) => typeof v === 'number' && STAGE_DISPLAY[k]);
    if (numericStages.length > 0) {
      const [domKey, domVal] = numericStages.reduce((a, b) => (b[1] > a[1] ? b : a));
      const gap = Math.abs(domVal - domScore);
      if (gap > 8) {
        const plainName = STAGE_PLAIN_NAME[domKey] || STAGE_DISPLAY[domKey];
        dominantExplain = `This score combines several checks, not just one. The strongest single signal here was our ${plainName}, which was ${domVal.toFixed(0)}% confident. The other checks found weaker support, which brought the overall score to ${domScore.toFixed(0)}%.`;
      }
    }
  }

  return (
    <div style={{
      background:cfg.bg, border:`1px solid ${cfg.border}`, borderRadius:8,
      padding:28, marginBottom:20,
    }}>
      <div style={{ display:'flex', gap:28, alignItems:'flex-start', flexWrap:'wrap' }}>

        {/* Dominant label — the headline number */}
        <div style={{ textAlign:'center', minWidth:160 }}>
          <div style={{
            fontSize:48, fontWeight:800, color:cfg.color, lineHeight:1,
            fontFamily:"'JetBrains Mono', monospace", letterSpacing:-1,
          }}>
            {domScore.toFixed(0)}%
          </div>
          <div style={{
            marginTop:8, display:'inline-block',
            fontSize:13, fontWeight:700, letterSpacing:2,
            color:cfg.color, border:`1px solid ${cfg.border}`,
            borderRadius:4, padding:'4px 12px', textTransform:'uppercase',
          }}>
            {cfg.icon} {cfg.label}
          </div>
          {riskLevel && (
            <div style={{ marginTop:6, fontSize:11, color:'#8da3c2', letterSpacing:1 }}>
              {riskLevel} RISK
            </div>
          )}
        </div>

        {/* Three-track bar breakdown */}
        <div style={{ flex:1, minWidth:200 }}>
          {tracks.length > 0 && (
            <div style={{ marginBottom:16 }}>
              {tracks.map(t => (
                <div key={t.label} style={{ marginBottom:10 }}>
                  <div style={{ display:'flex', justifyContent:'space-between', fontSize:11, color:'#8b949e', marginBottom:4 }}>
                    <span>{t.label}</span><span style={{ color:t.color, fontWeight:700 }}>{t.val.toFixed(1)}%</span>
                  </div>
                  <div style={{ height:5, background:'#234268', borderRadius:3, overflow:'hidden' }}>
                    <div style={{ height:'100%', width:`${t.val}%`, background:t.color, borderRadius:3, transition:'width 1s ease' }} />
                  </div>
                </div>
              ))}
            </div>
          )}
          <p style={{ fontSize:14, lineHeight:1.7, margin:0, color:'#c9d1d9' }}>{result.verdict}</p>
          {dominantExplain && (
            <div style={{ marginTop:12, paddingTop:12, borderTop:'1px solid #234268', display:'flex', gap:8, alignItems:'flex-start' }}>
              <span style={{ fontSize:14, color:'#5a7299', lineHeight:1.6, flexShrink:0 }}>ⓘ</span>
              <p style={{ fontSize:13, lineHeight:1.6, margin:0, color:'#8da3c2' }}>{dominantExplain}</p>
            </div>
          )}
          <div style={{ display:'flex', gap:8, marginTop:16 }}>
            <button
              onClick={async () => {
                // /report/{job_id} is now auth-gated (v6.0) — window.open() can't
                // carry an Authorization header, so fetch as a blob and trigger
                // a download manually instead.
                try {
                  const res = await authFetch(`/report/${result.job_id}`, authToken);
                  if (!res.ok) throw new Error(`Server returned ${res.status}`);
                  const blob = await res.blob();
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = `deepfake_report_${result.job_id}.pdf`;
                  document.body.appendChild(a);
                  a.click();
                  a.remove();
                  URL.revokeObjectURL(url);
                } catch (err) {
                  alert(`Could not download report: ${err.message}`);
                }
              }}
              style={{ background:'#00d4d4', color:'#070f1f', border:'none', borderRadius:5, padding:'9px 16px', fontSize:13, fontWeight:700, cursor:'pointer', display:'flex', alignItems:'center', gap:6 }}>
              <Download size={13} /> PDF Report
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Stage breakdown with explanations ─────────────────────────────────────────
function StageBreakdown({ stageScores }) {
  const [expanded, setExpanded] = useState(null);
  if (!stageScores) return null;

  const entries = Object.entries(stageScores).filter(([k, v]) =>
    v !== null && v !== undefined && STAGE_DISPLAY[k]
  );
  if (!entries.length) return null;

  // Mark the tile with the highest score as the "main signal" — gives the
  // user a visual anchor for which check is driving the verdict, since the
  // headline number is a blend and won't match any single tile exactly.
  const numericEntries = entries.filter(([, v]) => typeof v === 'number');
  const domKey = numericEntries.length
    ? numericEntries.reduce((a, b) => (b[1] > a[1] ? b : a))[0]
    : null;

  return (
    <div style={{ marginBottom:20 }}>
      <h3 style={{ fontSize:12, color:'#8da3c2', letterSpacing:1, textTransform:'uppercase', marginBottom:12 }}>
        Stage breakdown — click any stage for explanation
      </h3>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(140px, 1fr))', gap:10 }}>
        {entries.map(([key, val]) => {
          const isExp = expanded === key;
          const color = val >= 65 ? '#ef4444' : val >= 40 ? '#f59e0b' : '#10b981';
          return (
            <div key={key} onClick={() => setExpanded(isExp ? null : key)}
              style={{
                background: key === domKey ? '#18305a' : '#13294a',
                border:`1px solid ${isExp ? '#2dd4bf' : (key === domKey ? '#3a5a8a' : '#234268')}`,
                borderRadius:6, padding:14, cursor:'pointer', transition:'border-color 0.2s',
                position:'relative',
              }}>
              {key === domKey && (
                <span style={{
                  position:'absolute', top:10, right:10, fontSize:9, fontWeight:700,
                  letterSpacing:0.5, color:'#7fd4d4', background:'rgba(0,212,212,0.1)',
                  border:'1px solid rgba(0,212,212,0.25)', borderRadius:3, padding:'2px 6px',
                  textTransform:'uppercase',
                }}>
                  Main signal
                </span>
              )}
              <div style={{ fontSize:11, color:'#8da3c2', marginBottom:6, textTransform:'uppercase', letterSpacing:0.5 }}>
                {STAGE_DISPLAY[key]}
              </div>
              <div style={{ fontFamily:'monospace', fontSize:22, fontWeight:700, color, marginBottom:6 }}>
                {typeof val === 'number' ? `${val}%` : val}
              </div>
              <div style={{ height:3, background:'#234268', borderRadius:2, overflow:'hidden' }}>
                <div style={{ height:'100%', width:`${Math.min(val,100)}%`, background:color, borderRadius:2 }} />
              </div>
              {isExp && STAGE_EXPLAIN[key] && (
                <div style={{ marginTop:10, fontSize:12, color:'#8b949e', lineHeight:1.5, borderTop:'1px solid #234268', paddingTop:10 }}>
                  {STAGE_EXPLAIN[key]}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ── Lightbox ──────────────────────────────────────────────────────────────────
function Lightbox({ src, onClose }) {
  if (!src) return null;
  return (
    <div onClick={onClose} style={{
      position:'fixed', inset:0, background:'rgba(0,0,0,0.9)', zIndex:1000,
      display:'flex', alignItems:'center', justifyContent:'center', cursor:'zoom-out',
    }}>
      <img src={src} alt="" style={{ maxWidth:'92vw', maxHeight:'92vh', borderRadius:8, boxShadow:'0 24px 80px rgba(0,0,0,0.6)' }} />
      <button onClick={onClose} style={{
        position:'absolute', top:20, right:20, background:'rgba(255,255,255,0.1)',
        border:'none', borderRadius:'50%', width:36, height:36, cursor:'pointer',
        color:'#fff', fontSize:18, display:'flex', alignItems:'center', justifyContent:'center',
      }}><X size={16} /></button>
    </div>
  );
}

// ── Graphs grid ───────────────────────────────────────────────────────────────
function GraphsGrid({ graphs, jobId, authToken }) {
  const [lightbox, setLightbox] = useState(null);
  const [blobUrls, setBlobUrls] = useState({});

  // /graph/{job_id}/{filename} is now auth-gated (v6.0) — a plain <img src=...>
  // can't carry an Authorization header, so each graph is fetched here as an
  // authenticated request and converted to a local blob: URL instead.
  useEffect(() => {
    if (!graphs?.length || !jobId || !authToken) return;
    let cancelled = false;
    const createdUrls = [];

    (async () => {
      for (const g of graphs) {
        if (!g.filename) continue;
        try {
          const res = await authFetch(`/graph/${jobId}/${g.filename}`, authToken);
          if (!res.ok || cancelled) continue;
          const blob = await res.blob();
          if (cancelled) return;
          const url = URL.createObjectURL(blob);
          createdUrls.push(url);
          setBlobUrls(prev => ({ ...prev, [g.filename]: url }));
        } catch {
          // one graph failing to load shouldn't break the rest of the page —
          // it just stays in the "[ loading ]" state below
        }
      }
    })();

    return () => {
      cancelled = true;
      createdUrls.forEach(u => URL.revokeObjectURL(u));
    };
  }, [graphs, jobId, authToken]);

  if (!graphs?.length) return null;

  const getSrc = (g) => {
    if (g.filename && blobUrls[g.filename]) return blobUrls[g.filename];
    if (g.image_b64)                        return `data:image/png;base64,${g.image_b64}`;
    return null;
  };

  return (
    <>
      <Lightbox src={lightbox} onClose={() => setLightbox(null)} />
      <div style={{ marginBottom:20 }}>
        <h3 style={{ fontSize:12, color:'#8da3c2', letterSpacing:1, textTransform:'uppercase', marginBottom:12 }}>
          Visual analysis — click to expand
        </h3>
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:14 }}>
          {graphs.map((g, i) => {
            const src = getSrc(g);
            return (
              <div key={i} style={{ background:'#13294a', border:'1px solid #234268', borderRadius:6, overflow:'hidden', cursor: src ? 'zoom-in' : 'default' }}
                onClick={() => src && setLightbox(src)}>
                <div style={{ aspectRatio:'16/10', background:'#070f1f', display:'flex', alignItems:'center', justifyContent:'center' }}>
                  {src
                    ? <img src={src} alt={g.title} style={{ width:'100%', height:'100%', objectFit:'cover' }} />
                    : <span style={{ fontSize:11, color:'#5a7299', fontFamily:'monospace' }}>[ loading ]</span>
                  }
                </div>
                <div style={{ padding:'10px 12px' }}>
                  <div style={{ fontSize:12, fontWeight:600, color:'#e6edf3', marginBottom:3 }}>{g.title}</div>
                  <div style={{ fontSize:11, color:'#8da3c2', lineHeight:1.5 }}>{g.description}</div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
}

// ── Billing modal ──────────────────────────────────────────────────────────
function BillingModal({ authToken, currentPlan, onClose }) {
  const [busyPlan, setBusyPlan] = useState(null); // which plan button is loading
  const [error, setError] = useState('');

  const PLANS = [
    { id: 'monthly', name: 'Monthly', price: 'Contact for pricing', blurb: 'Higher analysis quota for regular use.' },
    { id: 'enterprise', name: 'Enterprise', price: 'Contact for pricing', blurb: 'For teams and high-volume insurance workflows.' },
  ];

  const subscribe = async (planId) => {
    setError(''); setBusyPlan(planId);
    try {
      const res = await authFetch(`/billing/checkout-session?plan=${planId}`, authToken, { method: 'POST' });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail || `Server returned ${res.status}`);
      window.location.href = data.checkout_url; // hand off to Stripe-hosted Checkout
    } catch (err) {
      setError(err.message);
      setBusyPlan(null);
    }
  };

  return (
    <div style={{ position:'fixed', inset:0, background:'rgba(7,15,31,0.75)', display:'flex', alignItems:'center', justifyContent:'center', zIndex:100 }}>
      <div style={{ background:'#13294a', border:'1px solid #234268', borderRadius:8, padding:28, width:420, maxWidth:'90vw' }}>
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:18 }}>
          <h2 style={{ fontSize:17, fontWeight:700, margin:0 }}>Upgrade plan</h2>
          <button onClick={onClose} style={{ background:'transparent', border:'none', color:'#8b949e', cursor:'pointer' }}><X size={18} /></button>
        </div>

        {currentPlan && (
          <div style={{ fontSize:12, color:'#8da3c2', marginBottom:16 }}>
            Current plan: <strong style={{ color:'#e6edf3' }}>{currentPlan.plan}</strong>
            {' — '}
            {currentPlan.monthly_quota > 100000
              ? 'unlimited analyses'
              : `${Math.max(0, currentPlan.monthly_quota - currentPlan.used_this_period)}/${currentPlan.monthly_quota} analyses left this period`}
          </div>
        )}

        {PLANS.map(p => (
          <div key={p.id} style={{ border:'1px solid #234268', borderRadius:6, padding:16, marginBottom:12 }}>
            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'baseline' }}>
              <span style={{ fontWeight:700, fontSize:15 }}>{p.name}</span>
              <span style={{ fontSize:13, color:'#8da3c2' }}>{p.price}</span>
            </div>
            <div style={{ fontSize:12, color:'#8da3c2', margin:'6px 0 12px' }}>{p.blurb}</div>
            <button
              onClick={() => subscribe(p.id)}
              disabled={busyPlan !== null || currentPlan?.plan === p.id}
              style={{
                width:'100%', background: currentPlan?.plan === p.id ? '#234268' : '#00d4d4',
                color: currentPlan?.plan === p.id ? '#8da3c2' : '#070f1f',
                border:'none', borderRadius:5, padding:'9px', fontSize:13, fontWeight:700,
                cursor: currentPlan?.plan === p.id ? 'default' : 'pointer',
              }}>
              {currentPlan?.plan === p.id ? 'Current plan' : (busyPlan === p.id ? 'Redirecting…' : `Subscribe to ${p.name}`)}
            </button>
          </div>
        ))}

        {error && <div style={{ color:'#ef4444', fontSize:12, marginTop:8 }}>{error}</div>}

        <div style={{ fontSize:11, color:'#6b7f9e', marginTop:12 }}>
          Payments are processed by Stripe in test mode — no real charge will occur.
        </div>
      </div>
    </div>
  );
}

// ── Auth gate ──────────────────────────────────────────────────────────────
function AuthGate({ onAuth }) {
  const [mode, setMode]       = useState('login'); // 'login' | 'signup'
  const [email, setEmail]     = useState('');
  const [password, setPassword] = useState('');
  const [error, setError]     = useState('');
  const [busy, setBusy]       = useState(false);

  const submit = async (e) => {
    e.preventDefault();
    setError(''); setBusy(true);
    try {
      const res = await fetch(`${API_BASE_URL}/auth/${mode}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail || `Server returned ${res.status}`);
      onAuth(data.access_token, email);
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div style={{ minHeight:'100vh', background:'#070f1f', color:'#e6edf3', display:'flex', alignItems:'center', justifyContent:'center', fontFamily:"'Inter', -apple-system, sans-serif" }}>
      <form onSubmit={submit} style={{ background:'#13294a', border:'1px solid #234268', borderRadius:8, padding:32, width:320 }}>
        <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:20 }}>
          <ShieldAlert size={20} color="#00d4d4" />
          <div>
            <div style={{ fontSize:9, fontWeight:600, color:'#00d4d4', letterSpacing:2, textTransform:'uppercase' }}>AlgorivX.AI</div>
            <div style={{ fontWeight:800, fontSize:18, color:'#e6edf3' }}>Darpan</div>
          </div>
        </div>
        <h2 style={{ fontSize:16, fontWeight:600, marginBottom:16 }}>{mode === 'login' ? 'Log in' : 'Create account'}</h2>
        <input type="email" placeholder="Email" value={email} required
          onChange={e => setEmail(e.target.value)}
          style={{ width:'100%', padding:'10px 12px', marginBottom:10, background:'#0f213d', border:'1px solid #234268', borderRadius:5, color:'#e6edf3', fontSize:14 }} />
        <input type="password" placeholder="Password" value={password} required minLength={8}
          onChange={e => setPassword(e.target.value)}
          style={{ width:'100%', padding:'10px 12px', marginBottom:14, background:'#0f213d', border:'1px solid #234268', borderRadius:5, color:'#e6edf3', fontSize:14 }} />
        {error && <div style={{ color:'#ef4444', fontSize:12, marginBottom:12 }}>{error}</div>}
        <button type="submit" disabled={busy} style={{ width:'100%', background:'#00d4d4', color:'#070f1f', border:'none', borderRadius:5, padding:'11px', fontSize:14, fontWeight:700, cursor:busy ? 'default' : 'pointer', marginBottom:10, opacity:busy?0.7:1 }}>
          {busy ? 'Please wait…' : (mode === 'login' ? 'Log in' : 'Sign up')}
        </button>
        <div style={{ textAlign:'center', fontSize:12, color:'#8da3c2' }}>
          {mode === 'login'
            ? <>No account? <span style={{ color:'#00d4d4', cursor:'pointer' }} onClick={() => { setMode('signup'); setError(''); }}>Sign up</span></>
            : <>Have an account? <span style={{ color:'#00d4d4', cursor:'pointer' }} onClick={() => { setMode('login'); setError(''); }}>Log in</span></>}
        </div>

        <div style={{ display:'flex', alignItems:'center', gap:10, margin:'18px 0' }}>
          <div style={{ flex:1, height:1, background:'#234268' }} />
          <span style={{ fontSize:11, color:'#6b7f9e' }}>OR</span>
          <div style={{ flex:1, height:1, background:'#234268' }} />
        </div>

        {/* Full page navigation, not fetch — OAuth requires a real browser
            redirect to the provider's own consent screen.
            Facebook login is intentionally not offered here yet — app
            registration was set aside for now. The backend route
            (/auth/facebook/login in oauth.py) is still there and returns a
            clean 503 if FACEBOOK_APP_ID isn't set, so re-adding this button
            later needs zero backend changes. */}
        <button type="button" onClick={() => { window.location.href = `${API_BASE_URL}/auth/google/login`; }}
          style={{ width:'100%', background:'#0f213d', color:'#e6edf3', border:'1px solid #234268', borderRadius:5, padding:'10px', fontSize:13, fontWeight:600, cursor:'pointer' }}>
          Continue with Google
        </button>
      </form>
    </div>
  );
}

// ── Main app ──────────────────────────────────────────────────────────────────
export default function DeepfakeDetectorApp() {
  const [stage, setStage]       = useState('upload');
  const [file, setFile]         = useState(null);
  const [progress, setProgress] = useState(0);
  const [result, setResult]     = useState(null);
  const [errorMsg, setErrorMsg] = useState('');
  const [dragActive, setDragActive] = useState(false);
  const fileInputRef       = useRef(null);
  const progressIntervalRef = useRef(null);

  const [authToken, setAuthToken] = useState(null);
  const [userEmail, setUserEmail] = useState('');
  const [authLoaded, setAuthLoaded] = useState(false);

  useEffect(() => {
    // OAuth callback (oauth.py) redirects here with '#auth_token=...&auth_email=...' —
    // fragments aren't sent to any server, so this is the only place that can read it.
    try {
      const hash = new URLSearchParams(window.location.hash.replace(/^#/, ''));
      const oauthToken = hash.get('auth_token');
      const oauthEmail = hash.get('auth_email');
      if (oauthToken && oauthEmail) {
        localStorage.setItem(AUTH_STORAGE_KEY, JSON.stringify({ token: oauthToken, email: oauthEmail }));
        setAuthToken(oauthToken);
        setUserEmail(oauthEmail);
        window.history.replaceState({}, '', window.location.pathname + window.location.search);
        setAuthLoaded(true);
        return;
      }
    } catch { /* malformed fragment — fall through to localStorage */ }

    try {
      const stored = localStorage.getItem(AUTH_STORAGE_KEY);
      if (stored) {
        const parsed = JSON.parse(stored);
        setAuthToken(parsed.token);
        setUserEmail(parsed.email);
      }
    } catch { /* corrupted or absent — treat as logged out */ }
    setAuthLoaded(true);
  }, []);

  const handleAuth = (token, email) => {
    localStorage.setItem(AUTH_STORAGE_KEY, JSON.stringify({ token, email }));
    setAuthToken(token);
    setUserEmail(email);
  };

  const handleLogout = () => {
    localStorage.removeItem(AUTH_STORAGE_KEY);
    setAuthToken(null);
    setUserEmail('');
    setStage('upload'); setFile(null); setProgress(0); setResult(null); setErrorMsg('');
  };

  // ── Billing ──────────────────────────────────────────────────────────────
  const [subscription, setSubscription] = useState(null); // {plan, status, monthly_quota, used_this_period}
  const [showBillingModal, setShowBillingModal] = useState(false);
  const [billingBanner, setBillingBanner] = useState(null); // 'success' | 'cancel' | null

  const refreshSubscription = useCallback(async (token) => {
    try {
      const res = await authFetch('/billing/subscription', token);
      if (res.ok) setSubscription(await res.json());
    } catch { /* non-fatal — plan/usage display just stays hidden */ }
  }, []);

  useEffect(() => {
    if (authToken) refreshSubscription(authToken);
  }, [authToken, refreshSubscription]);

  // Stripe redirects back to '/?billing=success' or '/?billing=cancel' after Checkout
  // (see billing.py — there's no separate /billing/success route in this single-page app).
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const params = new URLSearchParams(window.location.search);
    const billing = params.get('billing');
    if (billing === 'success' || billing === 'cancel') {
      setBillingBanner(billing);
      window.history.replaceState({}, '', window.location.pathname); // strip the query param
      if (billing === 'success' && authToken) refreshSubscription(authToken);
    }
  }, [authToken, refreshSubscription]);

  const handleFileSelect = useCallback((f) => { if (f) setFile(f); }, []);
  const handleDrag = (e) => {
    e.preventDefault(); e.stopPropagation();
    setDragActive(e.type === 'dragenter' || e.type === 'dragover');
  };
  const handleDrop = (e) => {
    e.preventDefault(); e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files?.[0]) handleFileSelect(e.dataTransfer.files[0]);
  };

  const startAnalysis = async () => {
    if (!file) return;
    setStage('scanning'); setProgress(0); setErrorMsg('');
    progressIntervalRef.current = setInterval(() => {
      setProgress(p => p < 92 ? p + Math.random() * 8 : p);
    }, 400);
    try {
      const fd = new FormData();
      fd.append('file', file);
      const res = await authFetch('/analyze', authToken, {
        method:'POST', headers:{'ngrok-skip-browser-warning':'true'}, body:fd,
      });

      if (res.status === 401) { clearInterval(progressIntervalRef.current); handleLogout(); return; }
      if (res.status === 429) {
        const q = await res.json().catch(() => ({}));
        clearInterval(progressIntervalRef.current);
        setErrorMsg(q.detail || 'Monthly analysis quota exceeded. Upgrade your plan to continue.');
        setStage('error');
        return;
      }
      if (!res.ok) throw new Error(`Server returned ${res.status}`);

      const queued = await res.json();
      const jobId = queued.job_id;

      // Backend records usage the moment the job is created (see main.py's
      // /analyze -> record_usage call), not when the analysis finishes — so
      // refresh the badge now, not after polling completes.
      refreshSubscription(authToken);

      // v6.0: /analyze returns immediately with a job_id — the actual pipeline
      // run happens async in the backend. Poll GET /jobs/{job_id} until it's
      // done or failed (5-minute ceiling, matching Render's own request limits).
      const POLL_MS = 2000;
      const MAX_ATTEMPTS = 150;
      let attempt = 0, finished = false;

      while (!finished && attempt < MAX_ATTEMPTS) {
        await new Promise(r => setTimeout(r, POLL_MS));
        attempt++;

        const statusRes = await authFetch(`/jobs/${jobId}`, authToken);
        if (statusRes.status === 401) { clearInterval(progressIntervalRef.current); handleLogout(); return; }
        if (!statusRes.ok) continue; // transient network/server hiccup — keep polling

        const statusData = await statusRes.json();

        if (statusData.status === 'done') {
          finished = true;
          clearInterval(progressIntervalRef.current);
          setProgress(100);
          const finalResult = { ...statusData.result, job_id: jobId };
          setTimeout(() => { setResult(finalResult); setStage('results'); }, 400);
        } else if (statusData.status === 'failed') {
          finished = true;
          clearInterval(progressIntervalRef.current);
          setErrorMsg(statusData.error || 'Analysis failed on the server.');
          setStage('error');
        }
        // else: still 'queued' or 'running' — loop continues
      }

      if (!finished) {
        clearInterval(progressIntervalRef.current);
        setErrorMsg(`Analysis is taking longer than expected and may still complete. Job ID: ${jobId}`);
        setStage('error');
      }
    } catch (err) {
      clearInterval(progressIntervalRef.current);
      setErrorMsg(`Could not reach the analysis server. It may be waking up — please wait 60 seconds and try again. (${err.message})`);
      setStage('error');
    }
  };

  const reset = () => { setStage('upload'); setFile(null); setProgress(0); setResult(null); setErrorMsg(''); };

  if (!authLoaded) return null; // avoid a flash of the login form while localStorage is checked
  if (!authToken) return <AuthGate onAuth={handleAuth} />;

  return (
    <div style={{ minHeight:'100vh', background:'#070f1f', color:'#e6edf3', fontFamily:"'Inter', -apple-system, sans-serif", position:'relative' }}>
      <style>{`
        * { box-sizing:border-box; }
        ::selection { background:#00d4d4; color:#070f1f; }
        @keyframes floatBubble { 0%,100%{transform:translateY(0) scale(1);} 33%{transform:translateY(-20px) scale(1.02);} 66%{transform:translateY(12px) scale(0.98);} }
        @keyframes scanline { 0%{transform:translateY(0);opacity:0.3;} 50%{opacity:1;} 100%{transform:translateY(400px);opacity:0.3;} }
        @keyframes pulse-ring { 0%{box-shadow:0 0 0 0 rgba(0,212,212,0.4);} 100%{box-shadow:0 0 0 16px rgba(0,212,212,0);} }
        @keyframes spin { to{transform:rotate(360deg);} }
        @keyframes fadeIn { from{opacity:0;transform:translateY(10px);} to{opacity:1;transform:translateY(0);} }
      `}</style>

      <Bubbles />

      {/* HEADER */}
      <header style={{
        borderBottom:'1px solid #1e3a5f', padding:'16px 32px',
        display:'flex', alignItems:'center', justifyContent:'space-between',
        // Solid distinct surface, not a translucent overlay of the page color —
        // the previous rgba(10,22,40,0.88) was a near-transparent version of the
        // page background itself, so the header always blended in regardless of
        // scroll position or backdrop blur. Now a step up the elevation ladder.
        background:'#0f213d', backdropFilter:'blur(12px)',
        position:'sticky', top:0, zIndex:100,
      }}>
        <div style={{ display:'flex', alignItems:'center', gap:10 }}>
          <ShieldAlert size={20} color="#00d4d4" />
          <div style={{ display:'flex', flexDirection:'column', gap:1 }}>
            <span style={{ fontSize:9, fontWeight:600, color:'#00d4d4', letterSpacing:2, textTransform:'uppercase', lineHeight:1 }}>AlgorivX.AI</span>
            <span style={{ fontWeight:800, fontSize:20, letterSpacing:-0.5, color:'#e6edf3', lineHeight:1 }}>Darpan</span>
          </div>
          <span style={{ fontFamily:'monospace', fontSize:10, color:'#00d4d4', border:'1px solid #234268', padding:'2px 6px', borderRadius:3, alignSelf:'flex-end', marginBottom:1 }}>
            FORENSIC ENGINE v 1.0
          </span>
        </div>
        <div style={{ display:'flex', alignItems:'center', gap:14, fontSize:13, color:'#8b949e' }}>
          {result && <button onClick={reset} style={{ background:'transparent', color:'#8b949e', border:'1px solid #234268', borderRadius:5, padding:'7px 12px', fontSize:12, cursor:'pointer' }}>New analysis</button>}
          {subscription && (
            <span style={{ fontSize:11, color:'#8da3c2', border:'1px solid #234268', borderRadius:5, padding:'5px 10px' }}>
              {subscription.plan} · {subscription.monthly_quota > 100000
                ? 'unlimited'
                : `${Math.max(0, subscription.monthly_quota - subscription.used_this_period)} left`}
            </span>
          )}
          <button onClick={() => setShowBillingModal(true)} style={{ background:'transparent', color:'#00d4d4', border:'1px solid #00d4d4', borderRadius:5, padding:'7px 12px', fontSize:12, cursor:'pointer', fontWeight:600 }}>Upgrade</button>
          <span style={{ fontSize:12 }}>{userEmail}</span>
          <button onClick={handleLogout} style={{ background:'transparent', color:'#8b949e', border:'1px solid #234268', borderRadius:5, padding:'7px 12px', fontSize:12, cursor:'pointer' }}>Log out</button>
        </div>
      </header>

      {billingBanner && (
        <div style={{
          maxWidth:960, margin:'12px auto 0', padding:'10px 16px', borderRadius:6, fontSize:13,
          background: billingBanner === 'success' ? 'rgba(16,185,129,0.12)' : 'rgba(239,68,68,0.10)',
          color: billingBanner === 'success' ? '#34d399' : '#f87171',
          border: `1px solid ${billingBanner === 'success' ? '#10b98155' : '#ef444455'}`,
          display:'flex', justifyContent:'space-between', alignItems:'center',
        }}>
          <span>{billingBanner === 'success' ? 'Subscription updated — thanks!' : 'Checkout was cancelled — no changes made.'}</span>
          <button onClick={() => setBillingBanner(null)} style={{ background:'transparent', border:'none', color:'inherit', cursor:'pointer' }}><X size={14} /></button>
        </div>
      )}

      {showBillingModal && (
        <BillingModal
          authToken={authToken}
          currentPlan={subscription}
          onClose={() => { setShowBillingModal(false); refreshSubscription(authToken); }}
        />
      )}

      <main style={{ maxWidth:960, margin:'0 auto', padding:'40px 24px 60px', position:'relative', zIndex:1 }}>

        {/* ── UPLOAD ── */}
        {stage === 'upload' && (
          <div style={{ animation:'fadeIn 0.4s ease' }}>
            <div style={{ marginBottom:32 }}>
              <h1 style={{ fontSize:28, fontWeight:700, margin:0, letterSpacing:-0.5 }}>Submit a file for analysis</h1>
              <p style={{ color:'#8b949e', fontSize:15, marginTop:8 }}>
                Images, video, audio, and documents. Multi-stage forensic pipeline — frequency analysis, face forensics, deep learning.
              </p>
            </div>

            <div onDragEnter={handleDrag} onDragLeave={handleDrag} onDragOver={handleDrag} onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
              style={{
                border:`2px dashed ${dragActive ? '#00d4d4' : '#234268'}`, borderRadius:8,
                padding:'56px 24px', textAlign:'center', cursor:'pointer',
                background: dragActive ? 'rgba(0,212,212,0.04)' : '#13294a', transition:'all 0.15s ease',
              }}>
              <input ref={fileInputRef} type="file" style={{ display:'none' }}
                onChange={e => handleFileSelect(e.target.files?.[0])}
                accept=".jpg,.jpeg,.png,.bmp,.tiff,.webp,.mp4,.avi,.mov,.mkv,.webm,.mp3,.wav,.aac,.flac,.ogg,.m4a,.pdf,.docx,.txt" />
              <Upload size={32} color="#00d4d4" style={{ marginBottom:16 }} />
              <div style={{ fontSize:16, fontWeight:600, marginBottom:6 }}>
                {file ? file.name : 'Drop a file here, or click to browse'}
              </div>
              <div style={{ fontSize:13, color:'#8da3c2' }}>
                {file ? formatBytes(file.size) : 'JPG · PNG · MP4 · MOV · MP3 · WAV · PDF · DOCX — up to 500 MB'}
              </div>
            </div>

            {file && (
              <div style={{ marginTop:16, display:'flex', gap:10 }}>
                <button onClick={startAnalysis} style={{ background:'#00d4d4', color:'#070f1f', border:'none', borderRadius:5, padding:'12px 24px', fontSize:14, fontWeight:700, cursor:'pointer', display:'flex', alignItems:'center', gap:8 }}>
                  Run analysis <ChevronRight size={16} />
                </button>
                <button onClick={() => setFile(null)} style={{ background:'transparent', color:'#8b949e', border:'1px solid #234268', borderRadius:5, padding:'12px 18px', fontSize:14, cursor:'pointer' }}>Clear</button>
              </div>
            )}

            <div style={{ marginTop:48, display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:12 }}>
              {[
                { icon:FileImage, label:'Images',    desc:'Frequency · Face · DL ensemble' },
                { icon:FileVideo, label:'Video',     desc:'Frame · Temporal consistency' },
                { icon:FileAudio, label:'Audio',     desc:'Voice clone · TTS detection' },
                { icon:FileText,  label:'Documents', desc:'AI-generated text detection' },
              ].map(item => (
                <div key={item.label} style={{ background:'#13294a', border:'1px solid #234268', borderRadius:6, padding:16 }}>
                  <item.icon size={18} color="#00d4d4" style={{ marginBottom:10 }} />
                  <div style={{ fontSize:13, fontWeight:600 }}>{item.label}</div>
                  <div style={{ fontSize:12, color:'#8da3c2', marginTop:4 }}>{item.desc}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── SCANNING ── */}
        {stage === 'scanning' && (
          <div style={{ animation:'fadeIn 0.3s ease' }}>
            <ScanningPanel fileName={file?.name} />
          </div>
        )}

        {/* ── ERROR ── */}
        {stage === 'error' && (
          <div style={{ background:'#13294a', border:'1px solid #ef4444', borderRadius:8, padding:32, textAlign:'center', animation:'fadeIn 0.3s ease' }}>
            <AlertTriangle size={28} color="#ef4444" style={{ marginBottom:16 }} />
            <div style={{ fontSize:16, fontWeight:600, marginBottom:8 }}>Analysis failed</div>
            <div style={{ fontSize:14, color:'#8b949e', marginBottom:24 }}>{errorMsg}</div>
            <button onClick={reset} style={{ background:'#234268', color:'#e6edf3', border:'none', borderRadius:5, padding:'10px 20px', fontSize:14, cursor:'pointer' }}>Try another file</button>
          </div>
        )}

        {/* ── RESULTS ── */}
        {stage === 'results' && result && (
          <div style={{ animation:'fadeIn 0.4s ease' }}>

            {/* Verdict hero — dominant classification */}
            <VerdictHero result={result} authToken={authToken} />

            {/* File info bar */}
            <div style={{ display:'flex', alignItems:'center', gap:10, padding:'10px 14px', background:'#13294a', border:'1px solid #234268', borderRadius:6, marginBottom:20, fontFamily:'monospace', fontSize:12, color:'#8da3c2', flexWrap:'wrap' }}>
              {React.createElement(FILE_ICONS[result.file_type] || FileText, { size:13, color:'#00d4d4' })}
              <span style={{ color:'#e6edf3' }}>{result.filename}</span>
              <span>·</span><span>{result.file_type}</span>
              <span>·</span><span>{formatBytes(result.metadata?.size_bytes)}</span>
              <span>·</span><span>Job {result.job_id}</span>
              {result.fusion_mode && <><span>·</span><span style={{ color:'#5a7299' }}>{result.fusion_mode}</span></>}
            </div>

            {/* Stage breakdown with explanations */}
            <StageBreakdown stageScores={result.stage_scores} />

            {/* Flagged indicators */}
            {result.indicators?.length > 0 && (
              <div style={{ marginBottom:20 }}>
                <h3 style={{ fontSize:12, color:'#8da3c2', letterSpacing:1, textTransform:'uppercase', marginBottom:12 }}>
                  Flagged indicators ({result.indicators.length})
                </h3>
                <div style={{ background:'#13294a', border:'1px solid #234268', borderRadius:6, overflow:'hidden' }}>
                  {result.indicators.map((ind, i) => (
                    <div key={i} style={{ display:'flex', alignItems:'flex-start', gap:10, padding:'10px 14px', fontSize:13, borderBottom: i < result.indicators.length-1 ? '1px solid #234268' : 'none' }}>
                      <AlertTriangle size={13} color="#f59e0b" style={{ flexShrink:0, marginTop:1 }} />
                      <span style={{ color:'#c9d1d9', lineHeight:1.5 }}>{ind}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Visual analysis graphs */}
            <GraphsGrid graphs={result.graphs} jobId={result.job_id} authToken={authToken} />

            {/* Detailed metrics */}
            {result.stats?.length > 0 && (
              <div style={{ marginBottom:20 }}>
                <h3 style={{ fontSize:12, color:'#8da3c2', letterSpacing:1, textTransform:'uppercase', marginBottom:12 }}>Detailed metrics</h3>
                <div style={{ display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:8 }}>
                  {result.stats.map((s, i) => (
                    <div key={i} style={{ background:'#13294a', border:'1px solid #234268', borderRadius:6, padding:'10px 12px' }}>
                      <div style={{ fontSize:10, color:'#8da3c2', marginBottom:3 }}>{s.label}</div>
                      <div style={{ fontFamily:'monospace', fontSize:13, color:'#e6edf3' }}>{s.value}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* File evidence */}
            <div>
              <h3 style={{ fontSize:12, color:'#8da3c2', letterSpacing:1, textTransform:'uppercase', marginBottom:12 }}>
                <Lock size={11} style={{ display:'inline', marginRight:5, verticalAlign:-1 }} /> File evidence
              </h3>
              <div style={{ background:'#13294a', border:'1px solid #234268', borderRadius:6, padding:14, fontFamily:'monospace', fontSize:11, color:'#8da3c2', lineHeight:2 }}>
                <div><span style={{ color:'#5a7299', marginRight:8 }}>MD5</span>{result.metadata?.md5}</div>
                <div><span style={{ color:'#5a7299', marginRight:8 }}>SHA256</span>{result.metadata?.sha256}</div>
                <div><span style={{ color:'#5a7299', marginRight:8 }}>MIME</span>{result.metadata?.mime}</div>
                <div><span style={{ color:'#5a7299', marginRight:8 }}>TIME</span>{result.metadata?.analyzed_at}</div>
              </div>
            </div>

          </div>
        )}
      </main>
    </div>
  );
}
